name: Makefile CI

on:
  push:
    branches: [ cicd-1 ]
  pull_request:
    branches: [ cicd-1 ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.6"

      - name: Install pipenv
        run: python -m pip install --upgrade pipenv wheel

      - id: cache-pipenv
        uses: actions/cache@v2
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install dependencies
        run: make init

      - name: Format Check
        run: make format-check

      - name: Lint
        run: make lint

      - name: Test
        run: make test-all
