name: Makefile CI

on:
  push:
    branches: [ cicd-1 ]
  pull_request:
    branches: [ cicd-1 ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.6"

      - name: Install pipenv
        run: python -m pip install --upgrade pipenv wheel

      - name: Install dependencies
        run: make init

  static-code-analysis:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: format check
        run: make format-check

      - name: lint
        run: make lint

      - name: test
        run: make test-all
