name: Makefile CI

on:
  push:
    branches: [ cicd-1 ]
  pull_request:
    branches: [ cicd-1 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: make init
      
    - name: format
      run: make format
      
    - name: lint
      run: make lint
